export default {
  USA: "",
  India: "in",
  France: "fr",
  Germany: "gm",
  Brazil: "",
  Japan: "",
  "S. Korea": "ks",
  Italy: "",
  UK: "",
  Russia: "",
  Turkey: "",
  Spain: "",
  Vietnam: "",
  Australia: "",
  Taiwan: "",
  Argentina: "",
  Netherlands: "",
  Iran: "",
  Mexico: "",
  Indonesia: "",
  Poland: "",
  Colombia: "",
  Austria: "",
  Greece: "",
  Portugal: "",
  Ukraine: "",
  Chile: "",
  Malaysia: "",
  Israel: "",
  Belgium: "",
  DPRK: "",
  Thailand: "",
  Czechia: "",
  Canada: "",
  Peru: "",
  Switzerland: "",
  Philippines: "",
  "South Africa": "",
  Romania: "",
  Denmark: "",
  "Hong Kong": "",
  Sweden: "",
  Serbia: "",
  Iraq: "",
  Singapore: "",
  "New Zealand": "",
  Hungary: "",
  Bangladesh: "",
  Slovakia: "",
  Georgia: "",
  Jordan: "",
  Ireland: "",
  Pakistan: "",
  Norway: "",
  Finland: "",
  Kazakhstan: "",
  Slovenia: "",
  Lithuania: "",
  Bulgaria: "",
  Morocco: "",
  Croatia: "",
  Guatemala: "",
  Lebanon: "",
  "Costa Rica": "",
  Bolivia: "",
  Tunisia: "",
  Cuba: "",
  Ecuador: "",
  UAE: "",
  Uruguay: "",
  Panama: "",
  Mongolia: "",
  Nepal: "",
  Belarus: "",
  Latvia: "",
  "Saudi Arabia": "",
  Azerbaijan: "",
  Paraguay: "",
  Bahrain: "",
  "Sri Lanka": "",
  Kuwait: "",
  "Dominican Republic": "",
  Cyprus: "",
  Myanmar: "",
  Palestine: "",
  Moldova: "",
  Estonia: "",
  Venezuela: "",
  Egypt: "",
  Libya: "",
  China: "",
  Qatar: "",
  Ethiopia: "",
  Réunion: "",
  Honduras: "",
  Armenia: "",
  "Bosnia and Herzegovina": "",
  Oman: "",
  "North Macedonia": "",
  Zambia: "",
  Kenya: "",
  Albania: "",
  Botswana: "",
  Luxembourg: "",
  Montenegro: "",
  Brunei: "",
  Algeria: "",
  Nigeria: "",
  Zimbabwe: "",
  Uzbekistan: "",
  Mozambique: "",
  Martinique: "",
  Laos: "",
  Afghanistan: "af",
  Iceland: "",
  Kyrgyzstan: "",
  Guadeloupe: "",
  "El Salvador": "",
  "Trinidad and Tobago": "",
  Maldives: "",
  Ghana: "",
  Namibia: "",
  Uganda: "",
  Jamaica: "",
  Cambodia: "",
  Rwanda: "",
  Cameroon: "",
  Malta: "",
  Barbados: "",
  Angola: "",
  "Channel Islands": "",
  "French Guiana": "",
  DRC: "",
  Senegal: "",
  Malawi: "",
  "Ivory Coast": "",
  Suriname: "",
  "New Caledonia": "",
  "French Polynesia": "",
  Eswatini: "",
  Guyana: "",
  Belize: "",
  Fiji: "",
  Madagascar: "",
  Sudan: "",
  Mauritania: "",
  "Cabo Verde": "",
  Bhutan: "",
  Syria: "",
  Burundi: "",
  Seychelles: "",
  Gabon: "",
  Andorra: "",
  "Papua New Guinea": "",
  Curaçao: "",
  Aruba: "",
  Tanzania: "",
  Mayotte: "",
  Mauritius: "",
  Togo: "",
  Guinea: "",
  "Isle of Man": "",
  Bahamas: "",
  Lesotho: "",
  "Faeroe Islands": "",
  Haiti: "",
  Mali: "",
  "Cayman Islands": "",
  "Saint Lucia": "",
  Benin: "",
  Somalia: "",
  Micronesia: "",
  Congo: "",
  "Solomon Islands": "",
  "San Marino": "",
  "Timor-Leste": "",
  "Burkina Faso": "",
  Liechtenstein: "",
  Gibraltar: "",
  Grenada: "",
  Bermuda: "",
  Nicaragua: "",
  "South Sudan": "",
  Tajikistan: "",
  "Equatorial Guinea": "",
  Tonga: "",
  Samoa: "",
  Monaco: "",
  "Marshall Islands": "",
  Dominica: "",
  Djibouti: "",
  CAR: "",
  Gambia: "",
  "Saint Martin": "",
  Vanuatu: "",
  Greenland: "",
  Yemen: "",
  "Caribbean Netherlands": "",
  "Sint Maarten": "",
  Eritrea: "",
  Niger: "",
  "St. Vincent Grenadines": "",
  "Guinea-Bissau": "",
  "Antigua and Barbuda": "",
  Comoros: "",
  Liberia: "",
  "Sierra Leone": "",
  Chad: "",
  "British Virgin Islands": "",
  "Cook Islands": "",
  "Saint Kitts and Nevis": "",
  "Turks and Caicos": "",
  "Sao Tome and Principe": "",
  Palau: "",
  "St. Barth": "",
  Nauru: "",
  Kiribati: "",
  Anguilla: "",
  Macao: "",
  "Saint Pierre Miquelon": "",
  "Wallis and Futuna": "",
  Tuvalu: "",
  "Saint Helena": "",
  "Falkland Islands": "",
  Montserrat: "",
  Niue: "",
  "Diamond Princess": "",
  "Vatican City": "",
  "Western Sahara": "",
  "MS Zaandam": "",
  Tokelau: "",
  undefined: "",
};
